#ifndef  _TYPES_H_
#define  _TYPES_H_

#include "cocos2d.h"

USING_NS_CC;

enum SushiType {
	SUSHI_TYPE_NORMAL = 0,
	SUSHI_TYPE_4_HORIZONTAL_LINE,
	SUSHI_TYPE_4_VERTICAL_LINE,
	SUSHI_TYPE_5_LINE,
	SUSHI_TYPE_5_CROSS,
};


enum GridType {
	GIRD_TYPE_NONE = 0,
	GIRD_TYPE_NORMAL,  // 1
	GRID_TYPE_JELLY,  // 2
	GRID_TYPE_DOUBLE_JELLY,  // 3
	GRID_TYPE_CREAM,  // 4
	GRID_TYPE_DOUBLE_CREAM,  // 5
};

#endif // _TYPES_H_

